Traceback (most recent call last):
  File "D:\ComputerScience\CODES\MatPlotAgent-main\workspace\example_86\code_action_gpt-4o_initial_0.py", line 21, in <module>
    fig, ax = plt.subplots(figsize=(10, 10), subplot_kw=dict(aspect="equal"))
  File "D:\miniconda3\lib\site-packages\matplotlib\pyplot.py", line 1598, in subplots
    fig = figure(**fig_kw)
  File "D:\miniconda3\lib\site-packages\matplotlib\pyplot.py", line 934, in figure
    manager = new_figure_manager(
  File "D:\miniconda3\lib\site-packages\matplotlib\pyplot.py", line 464, in new_figure_manager
    _warn_if_gui_out_of_main_thread()
  File "D:\miniconda3\lib\site-packages\matplotlib\pyplot.py", line 441, in _warn_if_gui_out_of_main_thread
    canvas_class = cast(type[FigureCanvasBase], _get_backend_mod().FigureCanvas)
  File "D:\miniconda3\lib\site-packages\matplotlib\pyplot.py", line 280, in _get_backend_mod
    switch_backend(rcParams._get("backend"))  # type: ignore[attr-defined]
  File "D:\miniconda3\lib\site-packages\matplotlib\pyplot.py", line 343, in switch_backend
    canvas_class = module.FigureCanvas
AttributeError: module 'backend_interagg' has no attribute 'FigureCanvas'. Did you mean: 'FigureCanvasAgg'?
